# Generated by Django 4.1.5 on 2023-01-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
